services:
  # Backend API Service Only (Frontend is on Vercel)
  - type: web
    name: restaurant-pos-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/debug/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: TZ
        value: Asia/Kolkata
    autoDeploy: true
    # Note: Free tier doesn't support persistent disks
    # Use PostgreSQL instead (see SWITCH_TO_POSTGRESQL_RENDER.md)

